const APP_CONSTANTS = {
  APP_NAME: 'M.R.S Traders WhatsApp Enquiry System',
  REQUEST_ID_HEADER: 'x-request-id',
  ENQUIRY_PREFIX: 'ENQ',
  ADMIN_PREFIX: 'ADM',
  ACTIVITY_PREFIX: 'ACT',
  DEFAULT_TIMEZONE: 'Asia/Kolkata',
  WHATSAPP_DEFAULT_CLIENT_ID: 'mrs-traders-primary',
  WHATSAPP_STATUS: {
    PENDING: 'PENDING',
    SENT: 'SENT',
    FAILED: 'FAILED',
    SKIPPED: 'SKIPPED'
  },
  ACTIVITY_TYPES: {
    REQUEST: 'REQUEST',
    ENQUIRY_CREATED: 'ENQUIRY_CREATED',
    WHATSAPP_SENT: 'WHATSAPP_SENT',
    WHATSAPP_FAILED: 'WHATSAPP_FAILED',
    HEALTH_CHECK: 'HEALTH_CHECK',
    ERROR: 'ERROR'
  }
};

module.exports = { APP_CONSTANTS };
